name: build-openboard
on: [push]
jobs:
  install-linux-3rdparty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: setup linux
        run: .github/scripts/setup-linux.sh
